// <auto-generated />
using System;
using FirstMud.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstMud.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstMud.Domain.Entities.BaseAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUpkeepAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextUpkeepDue")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("UpkeepCostAmount")
                        .HasColumnType("int");

                    b.Property<string>("UpkeepCostItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "AssetType");

                    b.ToTable("BaseAssets", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentLayer")
                        .HasColumnType("int");

                    b.Property<float>("DriftAccumulator")
                        .HasColumnType("real");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<string>("EvolutionBranch")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EvolutionTier")
                        .HasColumnType("int");

                    b.Property<int>("IgnoredWarnings")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPermanentlyGone")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationshipDepth")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UsageCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Companions", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Homestead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StorageSlots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Homesteads", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.HomesteadStorageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomesteadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomesteadId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("HomesteadStorageItems", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AppliedTaper")
                        .HasColumnType("int")
                        .HasColumnName("AppliedTaper");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscoveredByPlayerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<bool>("IsArdweldOrigin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSalvageable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWyrdTouched")
                        .HasColumnType("bit");

                    b.Property<int?>("MagicalElement")
                        .HasColumnType("int")
                        .HasColumnName("MagicalElement");

                    b.Property<int?>("MagicalPolarity")
                        .HasColumnType("int")
                        .HasColumnName("MagicalPolarity");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OriginWorld")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerId");

                    b.Property<int>("Quantity")
                        .HasDefaultValue(1)
                        .HasColumnType("int");

                    b.Property<int?>("TaperQuality")
                        .HasColumnType("int")
                        .HasColumnName("TaperQuality");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionPoints")
                        .HasColumnType("int");

                    b.Property<string>("ActiveCompanionIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActiveCompanionIds");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("CraftingSeed")
                        .HasColumnType("int");

                    b.Property<int>("CraftingSkill")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<bool>("ElementRevealed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EquippedAccessoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EquippedAccessoryId");

                    b.Property<Guid?>("EquippedArmorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EquippedArmorId");

                    b.Property<Guid?>("EquippedWeaponId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EquippedWeaponId");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Fortitude")
                        .HasColumnType("int");

                    b.Property<bool>("HasWyrdThread")
                        .HasColumnType("bit");

                    b.Property<int>("Intellect")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxActionPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxInventorySlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20)
                        .HasColumnName("MaxInventorySlots");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Polarity")
                        .HasColumnType("int");

                    b.Property<bool>("PolarityRevealed")
                        .HasColumnType("bit");

                    b.Property<int>("PrimaryElement")
                        .HasColumnType("int");

                    b.Property<int>("SalvageSkill")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<string>("UnlockedPortals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnlockedPortals");

                    b.Property<int>("WyrdTangle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.PlayerFactionReputation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPermanentFloor")
                        .HasColumnType("bit");

                    b.Property<int?>("PermanentFloor")
                        .HasColumnType("int")
                        .HasColumnName("PermanentFloor");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "FactionId")
                        .IsUnique();

                    b.ToTable("PlayerFactionReputations", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseWorkmanshipMax")
                        .HasColumnType("int");

                    b.Property<int>("BaseWorkmanshipMin")
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IngredientsJson");

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiredCraftingSkill")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredTaperType")
                        .HasColumnType("int")
                        .HasColumnName("RequiredTaperType");

                    b.Property<int>("RequiredWorld")
                        .HasColumnType("int");

                    b.Property<int>("ResultCategory")
                        .HasColumnType("int");

                    b.Property<string>("ResultItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.ResourceNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxYield")
                        .HasColumnType("int");

                    b.Property<int>("RegenerationRate")
                        .HasColumnType("int");

                    b.Property<int>("RemainingYield")
                        .HasColumnType("int");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("ResourceNodes", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AsciiSymbol")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncounterTableIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EncounterTableIds");

                    b.Property<bool>("IsPortalZone")
                        .HasColumnType("bit");

                    b.Property<string>("LootTableIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LootTableIds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PortalDestination")
                        .HasColumnType("int")
                        .HasColumnName("PortalDestination");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "ZoneId")
                        .IsUnique();

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Item", b =>
                {
                    b.OwnsOne("FirstMud.Domain.ValueObjects.Workmanship", "Workmanship", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("WorkmanshipValue");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Workmanship")
                        .IsRequired();
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("FirstMud.Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("World")
                                .HasColumnType("int")
                                .HasColumnName("WorldId");

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("PosX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("PosY");

                            b1.Property<int>("ZoneId")
                                .HasColumnType("int")
                                .HasColumnName("ZoneId");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("FirstMud.Domain.ValueObjects.Position", "SavedReturnPosition", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("World")
                                .HasColumnType("int")
                                .HasColumnName("SavedReturnWorldId");

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("SavedReturnPosX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("SavedReturnPosY");

                            b1.Property<int>("ZoneId")
                                .HasColumnType("int")
                                .HasColumnName("SavedReturnZoneId");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("FirstMud.Domain.ValueObjects.Weave", "Weave", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Current")
                                .HasColumnType("int")
                                .HasColumnName("CurrentWeave");

                            b1.Property<int>("Maximum")
                                .HasColumnType("int")
                                .HasColumnName("MaxWeave");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("SavedReturnPosition");

                    b.Navigation("Weave")
                        .IsRequired();
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.PlayerFactionReputation", b =>
                {
                    b.HasOne("FirstMud.Domain.Entities.Player", null)
                        .WithMany("Reputations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FirstMud.Domain.ValueObjects.ReputationScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("PlayerFactionReputationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Points")
                                .HasColumnType("int")
                                .HasColumnName("Points");

                            b1.HasKey("PlayerFactionReputationId");

                            b1.ToTable("PlayerFactionReputations");

                            b1.WithOwner()
                                .HasForeignKey("PlayerFactionReputationId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("FirstMud.Domain.Entities.Player", b =>
                {
                    b.Navigation("Reputations");
                });
#pragma warning restore 612, 618
        }
    }
}
